### ISSUE TITLE
Search support

### ISSUE THREAD

**Issue by kofalt** [flywheel-io/sdk#22]

**Comment by kofalt** [comment]
We'll need elasticsearch + mongo replication support in CI for search tests to pass :sunglasses:

**Comment by nagem** [comment]
This would involve creating a few structs, one to represent a SearchQuery, and one to represent a SearchResponse. For the SearchQuery, it would need to follow this format:
```
{
	"return_type": "file|acquisition|session|analysis",   # REQUIRED
	"search_string": "any string including spaces and special characters", # OPTIONAL KEY
	"all_data": true|false, # OPTIONAL, DEFAULTS TO FALSE
	"filters": [] # A LIST OF ES FILTERS, OPTIONAL KEY, find list of available filters here: https://www.elastic.co/guide/en/elasticsearch/reference/current/term-level-queries.html
}
```

And the SearchResponse would probably be a base SearchResponse, with specific <return_type>SearchResponse structs that inherit from it. A list of all keys returned can be found here:
https://github.com/scitran/core/blob/master/api/handlers/dataexplorerhandler.py#L325
and here:
https://github.com/scitran/core/blob/master/api/handlers/dataexplorerhandler.py#L385

**Comment by nagem** [comment]
@kofalt feel free to review the proposed structs above
