### ISSUE TITLE
High-level feature wishlist

### ISSUE THREAD

**Issue by kofalt** [flywheel-io/sdk#24]
This ticket tracks desired helper functions that would likely call more than one endpoint and do something helpful with the results. Features that would likely call only one endpoint will be tracked on [the server repo](https://github.com/scitran/core) with a note that SDK exposure would be helpful.

1. Visitor pattern. Start from a resolver-string-path, visit each children node in consistent order. Could be helpful for intuitive search/filter-like use cases.
2. Pass a directory with DICOM files to the SDK to then be zipped and uploaded to an acquisition
3. Get a project by 'label'
4. Get a gear by name
5. Run a batch on files found from a search
6. ~Get file info given the filename and acq_id~

**Comment by jenreiter** [comment]
Here are some other higher level functionality based off of Brian's scitran client

1. Get all sessions and acquisitions within a project 
https://github.com/scitran/client/blob/master/%40scitran/projectHierarchy.m
2. I like the idea of grabbing groups of files that would be needed for computation, i.e. load a nifti, bvec and bval from a Flywheel acquisition. This could be useful for other Gears/use cases such as the HCP pipelines or spectral data analysis
https://github.com/scitran/client/blob/master/%40scitran/dwiLoad.m
3. Put analysis 
https://github.com/scitran/client/blob/master/%40scitran/putAnalysis.m

**Comment by kofalt** [comment]
> Get all sessions and acquisitions within a project

We have the former; [GetProjectSessions](https://godoc.org/github.com/flywheel-io/sdk/api#Client.GetProjectSessions).

**Comment by jenreiter** [comment]
Feedback from Gunnar that was circled back to me:

Downloadable file URLs
Container by path
Standard search functions (e.g., file in project by name)
Simple file upload
Download file into memory
Visitor pattern (tree walker)
JSON flattener

**Comment by kofalt** [comment]
* We need more info on "Standard search functions", my guess is you're on that :)
* Download file into memory is probably not feasible.
* What's meant by "json flattener"?

**Comment by kofalt** [comment]
Function signatures:

1. Visitor - frontend specific, python example: `for node in fw.Walk('scitran/Nueroscience')`
    High value, maps to use cases where you're inspecting the tree. Implementation effort.
1. Packfile upload: `fw.UploadDirectory('container_type', 'container_id', 'folder', 'type')` ideally becomes `fw.UploadDirectory('container_id', 'folder', 'type')`
    High value, low effort, no new implementation required.
1. Resolve to single container: `fw.Lookup('scitran/Nueroscience/ex1')`

**Comment by nagem** [comment]
Search now allows `size=all` and `simple=true`, which would improve search QOL for the SDK.

**Comment by kofalt** [comment]
Both the simpler format and the size option is landing in #53.

**Comment by jenreiter** [comment]
The function signatures have been placed into an Aha card

**Comment by jenreiter** [comment]
Issues from Imad's SDK gear writing...

1. If a file is given,

**Comment by lmperry** [comment]
Download container by ID would be on my wish list. This exists in the CLI, would be nice to have something similar in the SDK - it would prevent a whole lot of looping going on.
