### ISSUE TITLE
Python wheel!

### ISSUE THREAD

**Issue by kofalt** [flywheel-io/sdk#25]
At the OHBM preconference event, my project colleague Julia wrote a setup.py file:
https://github.com/kofalt/cbstools-public/blob/master/pypi/setup.py

I later took that file, and used it to produce a wheel file:
https://github.com/kofalt/cbstools-public/commit/c2187ebb3b389096fcffc10b27c7614241cb3a57

Things:

1. Add a `setup.py` file to `bridge/dist/python`. Don't forget to set `package_data` for our `.so` file.
1. Try the command from the second link to build a wheel.
1. If that works, send the command to me and I'll add it to our CI (maybe).
1. Bonus: see if you can figure out how to specify the architecture of the created wheel. This would let us have one wheel per architecture, (so... two) rather than the files being ambiguous.

**Comment by ryansanford** [comment]
@kofalt 
Is cross-compile for linux/darwin possible, or do we need to find separate CI vendor that supports OSX?

**Comment by kofalt** [comment]
Good question, but something we should tackle separately. I'll add another ticket.
