### ISSUE TITLE
Offer a simplified search results format

### ISSUE THREAD

**Issue by nagem** [flywheel-io/sdk#37]
Currently the `Search()` function returns search results in the format the API returns results, which is 

```
{
    "results": [
        {"_id": "<Elastic-id>", "_source": {<the-actual-doc-result>}}
    ]
}
```

This is useful for clients that would need pagination/count/match score/elastic id information, but it cumbersome for users just looking for a list of the results:

(Using the python SDK):
```
files = [ x['_source'] for x in fw.search({
    'return_type': 'file',
    'filters': [
        {'match': {'collection.label': 'ENGAGE'}},
        {'match': {'acquisition.label': 'T1w 1mm'}}
    ]
}).get('results', []) ]
```

Either a new function that wraps and reformats `Search()` or directly reformating the results of `Search()` would be helpful for usability.

**Comment by kofalt** [comment]
I like this idea! From offline discussion:

1. We'd probably offer this format via `Search()`, and move the current format to `SearchRaw()`
1. This format be offered server-side; something like `&simple=bool` on the endpoint
1. We'll probably bundle this with other search functions whenever we add convenience search functions.

**Comment by hkethi002** [comment]
So for clarification are we just making a new function wrapper that returns a cleaner result, or are we calling the endpoint with a new parameter that will return the result in a different format which we will need to store in a new struct?

**Comment by kofalt** [comment]
The later. But this can wait until we want to add other functions as per my above comment.
