### ISSUE TITLE
Search for a file does not return the file ID, needed for downloading

### ISSUE THREAD

**Issue by wandell** [flywheel-io/sdk#54]
Can you please confirm that the arguments to

           downloadFileFromSession(id, name, path)

the file id in the database, the intended name for the downloaded file, and the path to the local file.

If so, a search result should contain the file.x_id somewhere, so I can search and download based on the result.  I can't find the file id, although the id of other objects (sessions, project) are included.

Here is what a search result of a file looks like to me.

```
files{1}

ans = 

  struct with fields:

        project: [1×1 struct]
          group: [1×1 struct]
        session: [1×1 struct]
        subject: [1×1 struct]
           file: [1×1 struct]
    permissions: [11×1 struct]
         parent: [1×1 struct]

>> files{1}.file

ans = 

  struct with fields:

    measurements: {'localizer'}
            type: 'nifti'
            name: '11347_7_1.nii.gz'
            size: 44581727
```

Thanks,
Brian

**Comment by wandell** [comment]
Or, maybe id is the parent.x_id, name is the name of the file, and path is a full path (including file name) to the output file?  

Anyway, when I tried that, something downloaded. It didn't have the right format, so this guess is probably not correct.

**Comment by kofalt** [comment]
Your idea from the second comment is correct.

I'm not sure what you mean by not having the wrong format. Could you check the `parent.type` or print that out here? It's possible the parent type was not a session, in which case you got a wrong file.

I really wouldn't expect that though, as the container IDs should never overlap. `downloadFileFromSession` should definitely either throw an error or get the right file :slightly_smiling_face:

**Comment by wandell** [comment]
Thanks, I see.  I will spend more time with the testDrive.m script and see if I can't figure it out.  I wasn't aware of that set of examples.  Now that I know, off we go.
