### ISSUE TITLE
If `get_session_acquisitions` called on an analyses ID, no error raised, just empty list returned

### ISSUE THREAD

**Issue by jenreiter** [flywheel-io/sdk#57]
An analyses ID was passed to the function, `get_session_acquisitions`,  and no error was raised...

Below is an example from the python SDK.

```
>>> analyses_id = '59e7c065b362eb0018374a62'
>>> acqs = fw.get_session_acquisitions(analyses_id)
>>> acqs
[]
```

**Comment by kofalt** [comment]
Well, that's technically correct! :tada:
